language: java
addons:
  apt:
    packages:
      - oracle-java8-installer
jdk:
  - oraclejdk8
notifications:
  irc:
    channels:
      - "open.ircnet.net#ohtufubar"
    template:
      - "%{repository} (%{commit}) : %{message} %{foo} "
      - "Build details: %{build_url}"
